-- MySQL Script generated by MySQL Workbench
-- Fri May  8 16:06:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema scheduling
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scheduling
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scheduling2` DEFAULT CHARACTER SET utf8mb4 ;
USE `scheduling2` ;

-- -----------------------------------------------------
-- Table `scheduling`.`coursedetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduling2`.`coursedetails` (
  `cono` VARCHAR(10) NOT NULL,
  `labhr` INT(5) NOT NULL,
  `lechr` INT(5) NOT NULL,
  PRIMARY KEY (`cono`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `scheduling`.`roomweek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduling2`.`roomweek` (
  `roomno` VARCHAR(10) NOT NULL,
  `room availibility` VARCHAR(10) NULL DEFAULT NULL,
  `monday` INT(11) NULL DEFAULT NULL,
  `tuesday` INT(11) NULL DEFAULT NULL,
  `wednesday` INT(11) NULL DEFAULT NULL,
  `thursday` INT(11) NULL DEFAULT NULL,
  `friday` INT(11) NULL DEFAULT NULL,
  `saturday` INT(11) NULL DEFAULT NULL,
  `sunday` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`roomno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `scheduling`.`scheduledtimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduling2`.`scheduledtimes` (
  `secno` INT(5) NOT NULL,
  `DayMeet1` VARCHAR(10) NOT NULL,
  `DayMeet2` VARCHAR(10) NULL DEFAULT NULL,
  `DayMeet3` VARCHAR(10) NULL DEFAULT NULL,
  `StartTime1` VARCHAR(15) NOT NULL,
  `StartTime2` VARCHAR(15) NULL DEFAULT NULL,
  `StartTime3` VARCHAR(15) NULL DEFAULT NULL,
  `EndTime1` VARCHAR(15) NOT NULL,
  `EndTime2` VARCHAR(15) NULL DEFAULT NULL,
  `EndTime3` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`secno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `scheduling`.`sectiondetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduling2`.`sectiondetails` (
  `secno` INT(5) NOT NULL,
  `roomno` VARCHAR(10) NOT NULL,
  `cono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`secno`, `roomno`, `cono`))
	ENGINE = InnoDB
	DEFAULT CHARACTER SET = utf8mb4;


ALTER TABLE `scheduling2`.`sectiondetails`;
	CREATE INDEX fk_roomno_idx ON sectiondetails (roomno);
ALTER TABLE `scheduling2`.`sectiondetails`
ADD CONSTRAINT FOREIGN KEY fk_roomno_idx (roomno) 
    REFERENCES roomweek(roomno)
    ON DELETE RESTRICT
	ON UPDATE CASCADE;
    
ALTER TABLE `scheduling2`.`sectiondetails`;
	CREATE INDEX fk_cono_idx ON sectiondetails (cono);
ALTER TABLE `scheduling2`.`sectiondetails`
ADD CONSTRAINT FOREIGN KEY fk_cono_idx (cono) 
    REFERENCES coursedetails(cono)
    ON DELETE RESTRICT
	ON UPDATE CASCADE;
    
ALTER TABLE `scheduling2`.`sectiondetails`;
	CREATE INDEX secno_idx ON sectiondetails (secno);
ALTER TABLE `scheduling2`.`sectiondetails`
ADD CONSTRAINT FOREIGN KEY fk_secno_idx (secno) 
    REFERENCES scheduledtimes(secno)
    ON DELETE RESTRICT
	ON UPDATE CASCADE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
